apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ___APP_NAME___
spec:
  #schedule: "*/2 * * * *"
  schedule: "15 3 * * 1-5"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ___APP_NAME___
            image: ___DOCKER_REGISTRY_URL___/___DOCKER_REGISTRY_NAMESPACE___/___APP_NAME___:___APP_TAG___
          restartPolicy: OnFailure
